package com.wavemaker.secureauth.callservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import jakarta.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.fasterxml.jackson.databind.JsonNode;
import com.secureauth.utils.StandardResponse;
import com.wavemaker.secureauth.callservice.CallService;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link CallService}.
 * @see CallService
 */
@RestController
@Api(value = "CallController", description = "controller class for java service execution")
@RequestMapping("/call")
public class CallController {

    @Autowired
    private CallService callService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @PostMapping(value = "/callVerifyMethod")
    public ResponseEntity<StandardResponse> callVerifyMethod(@RequestBody JsonNode jsonNode,  HttpServletRequest request) {
        return callService.callVerifyMethod(jsonNode, request);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @GetMapping(value = "/sampleJavaOperation")
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name,  HttpServletRequest request) {
        return callService.sampleJavaOperation(name, request);
    }
}

